In [3]:
!pip install numpy

^C
Note: you may need to restart the kernel to use updated packages.


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.3 MB 4.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.3 MB 4.6 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.3 MB 4.0 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.3 MB 4.0 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/12.3 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.3 MB 2.7 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.3 MB 2.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.2/12.3 MB 2.8 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.3 MB 3.0 MB/s eta 0:00:03
   ---------------------- ----------------- 6.8/12.3 MB 3.1 MB/s eta 0:00:02
   ----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [7]:
import numpy as np

## Create arrays using 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   #1-Row & 5-Cols
# There is 5 elements in the array, but if we reshape it into 1,4 it will throw error.
# arr2.reshape(1,4)

array([[1, 2, 3, 4, 5]])

In [11]:
# 2D Array
arr3 = np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [3 4 5 6 7]]
(2, 5)


In [22]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape: ",arr.shape)
print("Number Of Dimension: ",arr.ndim)
print("Number of elements: ",arr.size)
print("Data Type",arr.dtype)
print("Item Size(in Bytes): ",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number Of Dimension:  2
Number of elements:  6
Data Type int64
Item Size(in Bytes):  8


In [32]:
# Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Elementwise addition
print("Addition ",arr1+arr2)

#Elementwise substraction
print("Subraction ",arr2-arr1)

#Elementwise Multiplication
print("Subraction ",arr2*arr1)

#Elementwise Division
print("Subraction ",arr2/arr1)

Addition  [11 22 33 44 55]
Subraction  [ 9 18 27 36 45]
Subraction  [ 10  40  90 160 250]
Subraction  [10. 10. 10. 10. 10.]


In [34]:
#Universal Functions
arr = np.array([1,2,3,4,5])

## Square Root
print(np.sqrt(arr))

## Exponential
print(np.sqrt(arr))

## Sine
print(np.sin(arr))

##Natural Log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [37]:
## Array Slicing & Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
print(arr[0][0])

1


In [46]:
## Suppose we need to print 
## 7   8
## 11 12

print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [55]:
# print(arr[0:2,2:])
# print(arr[1:,0:2])

[[ 5  6]
 [ 9 10]]


In [59]:
## Modify array elements
arr[0,0] = 100
print(arr)

arr[1:] = 100 ## Everything right after the 1 row will be replaced by 100

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [60]:
## Statistical concepts
data = np.array([1,2,3,4,5,6,7,8,9,10])
# Mean
mean = np.mean(data)
print('Mean: ',mean)

#Median
median = np.median(data)
print('Median: ',median)

#Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ",std_dev)

#Variance
variance = np.var(data)
print("Variance: ",variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [ ]:
#Logical Operations - Important For Pandas.

data > 5  #Output: array([False, False, False, False, False,  True,  True,  True,  True,True])

data[(data>=5) & (data<=8)] #Output: array([5, 6, 7, 8])